name: Deploy Resonance Backend to Azure

on:
  push:
    branches:
      - main
    paths:
      branches
       - main  
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Create virtual environment
        working-directory: ./backend
        run: |
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        working-directory: ./backend
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Create deployment package
        working-directory: ./backend
        run: |
          zip -r ../backend-deploy.zip . \
            -x "venv/*" \
            -x "__pycache__/*" \
            -x "*.pyc" \
            -x ".env" \
            -x ".git/*" \
            -x "*.db"

      - name: Upload artifact for deployment
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: backend-deploy.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip deployment package
        run: |
          mkdir backend-app
          unzip backend-deploy.zip -d backend-app

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'resonance-backend-spandanap'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
          package: backend-app

